### ISSUE TITLE
Add Windows and 1.18 support by switching to Meson

### ISSUE THREAD

**Issue by joshdoe** [conda-forge/gst-python-feedstock#8]
Now that [gstreamer-feedstock has added Windows support](https://github.com/conda-forge/gstreamer-feedstock/pull/43), it seems a good time to add Windows and 1.18 support to gst-python. I've already gotten rusty with modifying feedstock, so I'm guessing someone might get to this before me.

**Comment by tschoonj** [comment]
Done in #9
